spring.application.name=jpa

# Active Profile
spring.profiles.active=dev

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.io.goorm.jpa=DEBUG

# Error 로그 출력
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-exception=true
