spring.application.name=jpa

# Active Profile
spring.profiles.active=jpa



# Internationalization
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
